### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by maltehi** [maltehi/outlook-taskboard#17]
Loading of the task board can take quite long, especially when many tasks have to be displayed. This can have a considerable impact on the workflow, since the taskboard is reloaded after any task is changed in order to keep the overview up to date.

The process of loading the tasks from Outlook should be looked into and, if possible, made more efficient.

**Comment by GrimmiMeloni** [comment]
For what it's worth, I took a quick glimpse add it with the IE11 profiler. I don't think the loading from outlook is the actual culprit, but rather the mass DOM modification that happens. At least I see lots of "pressure" coming from the angular internals. I hunted around a bit, and found that ng-repeats are a common cause of this. I tried using a "one-time binding" (via a :: notation) in the template. That works - but it did not give me significant speed ups, because for whatever reason that triggered a full page reload whenever an item changed lanes. I put this to the side for now again, as my board is still rather small (<50 items) and I consider it fast enough.

**Comment by maltehi** [comment]
Thanks for the analysis! It turned out that a major factor slowing my taskboard down was opening it in Internet Explorer. In the meantime, I went back to displaying it in Outlook as a home page, which is much faster.

Still keeping this open, in case someone feels like making some improvements here.
