### ISSUE TITLE
Status Report 

### ISSUE THREAD

**Issue by fredericbreysse** [maltehi/outlook-taskboard#6]
Hello maltehi,
First of all I wanted to thank you for your work, I have been using it for 1 year now and I find this tool really effective. i love it !!
I don't know if I'm in the right place to ask this question, but I'm going to do it.

How can we make sure that in the Status Report the information of each task appears ( ##to do, ##status, ##issues, ##reference)?

I don't know if I'm perfectly clear in my request... but thank you in advance

**Comment by maltehi** [comment]
Hi Frederic,

Thanks for the feedback, I'm glad the taskboard works for you.

I'm not sure I understood exactly what your question is, though. By default, the information of all tasks currently displayed in the taskboard view should be summarized in the status report, which includes the task notes. What you referred to (##to do, ....) seemed to be the template for the task notes, which you can also adapt in the configuration.

If you also want tasks that are not currently displayed (due to a filter) to appear in the status report, you can set the config parameter FILTER_REPORTS to false. Hope that helps!

Malte
